# Copyright 2025-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.13.5

EAPI=8

CRATES="
"

LLVM_COMPAT=( 21 22 )
RUST_MIN_VER="1.92.0"
RUST_NEEDS_LLVM=1
inherit cargo gnome2-utils llvm-r1 meson toolchain-funcs xdg

DESCRIPTION="A simple Emby Client written by GTK4-RS"
HOMEPAGE="https://github.com/tsukinaha/tsukimi"
SRC_URI="
	https://github.com/tsukinaha/tsukimi/archive/refs/tags/v${PV}.tar.gz
		-> ${P}.tar.gz
	https://github.com/gentoo-zh-drafts/tsukimi/releases/download/v${PV}/${P}-crates.tar.xz
	${CARGO_CRATE_URIS}
"

LICENSE="GPL-3"
# Dependent crate licenses
LICENSE+="
	Apache-2.0 Apache-2.0-with-LLVM-exceptions BSD-2 BSD Boost-1.0
	CDLA-Permissive-2.0 ISC LGPL-2.1 MIT MPL-2.0 Unicode-3.0 ZLIB
"
SLOT="0"
KEYWORDS="~amd64"

IUSE="clang"

QA_PRESTRIPPED="/usr/bin/tsukimi"

RDEPEND="
	>=gui-libs/gtk-4.22
	>=gui-libs/libadwaita-1.9
	media-libs/glycin-loaders:2=
	media-libs/gst-plugins-base:1.0
	media-libs/gstreamer
	media-video/mpv
	sys-libs/libseccomp
"

DEPEND="
	${RDEPEND}
	media-libs/glycin
	media-libs/gst-plugins-bad:1.0
"
BDEPEND="
	clang? (
		$(llvm_gen_dep '
			llvm-core/clang:${LLVM_SLOT}
			llvm-core/llvm:${LLVM_SLOT}
			llvm-core/lld:${LLVM_SLOT}
		')
	)
	>=dev-util/blueprint-compiler-0.20.4
"

pkg_setup() {
	if use clang && ! tc-is-clang; then
		llvm-r1_pkg_setup
		export CC=clang
		export CXX=clang++
		export AR=llvm-ar
		export NM=llvm-nm
		export STRIP=llvm-strip
		export RANLIB=llvm-ranlib
	fi
	rust_pkg_setup
}

src_configure () {
	cargo_gen_config
	local emesonargs=(
		-Dsandboxed-build=true
	)
	meson_src_configure
	ln -s "${CARGO_HOME}" "${S}/cargo" || die
}

pkg_postinst() {
	xdg_pkg_postinst
	gnome2_schemas_update
}

pkg_postrm() {
	xdg_pkg_postrm
	gnome2_schemas_update
}
