#!/sbin/openrc-run
# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

description="Network Time Service (ntpd-rs)"

command="/usr/bin/ntp-daemon"
command_args="${NTPD_RS_ARGS}"
command_background="true"
command_user="ntpd-rs:ntpd-rs"
capabilities="^cap_sys_time,^cap_net_bind_service"
pidfile="/run/${RC_SVCNAME}.pid"

export RUST_LOG="${RUST_LOG:-info}"

depend() {
	need net
}

start_pre() {
	checkpath -d -m 0755 -o ntpd-rs:ntpd-rs /run/ntpd-rs
}
