# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.17.1

EAPI=8

CRATES="
"

RUST_MIN_VER="1.90"

inherit cargo

DESCRIPTION="Fast fuzzy finder for coding agent session history"
HOMEPAGE="https://github.com/angristan/fast-resume"
SRC_URI="
	https://github.com/angristan/fast-resume/archive/refs/tags/v${PV}.tar.gz -> ${P}.tar.gz
	https://github.com/gentoo-zh-drafts/${PN}/releases/download/v${PV}/${P}-crates.tar.xz
"

LICENSE="MIT"
# Dependent crate licenses
LICENSE+="
	Apache-2.0 Boost-1.0 MIT MPL-2.0 Unicode-3.0 Unicode-DFS-2016
	WTFPL-2 ZLIB
"
SLOT="0"
KEYWORDS="~amd64"
